# Generated by Django 4.1.5 on 2023-02-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='avatar',
            field=models.ImageField(default=None, upload_to='messenger/static/messenger/serveravatars'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default=None, upload_to='messenger/static/messenger/useravatars'),
        ),
    ]
