# Generated by Django 4.1.5 on 2023-02-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_alter_chat_avatar_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='avatar',
            field=models.ImageField(default=None, upload_to='messenger/serveravatars'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default=None, upload_to='messenger/useravatars'),
        ),
    ]
