# Generated by Django 4.1.5 on 2023-02-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_alter_chat_avatar_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='name',
            field=models.CharField(default='Chat name', max_length=32),
        ),
    ]
