# Generated by Django 4.1.5 on 2023-03-05 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0005_chat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='txt',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default=None, null=True, upload_to='messenger/static/messenger/useravatars'),
        ),
        migrations.AlterField(
            model_name='user',
            name='chats',
            field=models.ManyToManyField(blank=True, null=True, to='messenger.chat'),
        ),
    ]
