# Generated by Django 4.1.5 on 2023-03-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0007_remove_chat_admins_alter_user_chats'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='link',
            field=models.TextField(default=None, max_length=128),
        ),
    ]
